
export interface Wildcard {
  id: number;
  category: string;
  text: string;
}

export const wildcards: Wildcard[] = [
  { id: 1, category: "FEEL YOUR PAIN", text: "Act out 'Walking on hot coals'." },
  { id: 2, category: "FEEL YOUR PAIN", text: "Act out 'Winning the lottery'." },
  { id: 3, category: "FEEL YOUR PAIN", text: "Act out 'Getting a root canal'." },
  { id: 4, category: "FEEL YOUR PAIN", text: "Act out 'Running a marathon'." },
  { id: 5, category: "FEEL YOUR PAIN", text: "Act out 'Being audited by the IRS'." },
  { id: 6, category: "FEEL YOUR PAIN", text: "Act out 'Scuba diving with sharks'." },
  { id: 7, category: "FEEL YOUR PAIN", text: "Act out 'Climbing Mount Everest'." },
  { id: 8, category: "FEEL YOUR PAIN", text: "Act out 'A bad hair day'." },
  { id: 9, category: "FEEL YOUR PAIN", text: "Act out 'Being chased by a bear'." },
  { id: 10, category: "FEEL YOUR PAIN", text: "Act out 'Trying to assemble IKEA furniture'." },
  { id: 11, category: "FEEL YOUR PAIN", text: "Act out 'A first date'." },
  { id: 12, category: "FEEL YOUR PAIN", text: "Act out 'Getting pulled over by the police'." },
  { id: 13, category: "FEEL YOUR PAIN", text: "Act out 'Waking up late for an important meeting'." },
  { id: 14, category: "FEEL YOUR PAIN", text: "Act out 'Trying to kill a spider'." },
  { id: 15, category: "FEEL YOUR PAIN", text: "Act out 'A toddler's temper tantrum'." },
  { id: 16, category: "PARTY PLATFORM", text: "Draw 'A political debate'." },
  { id: 17, category: "PARTY PLATFORM", text: "Draw 'The Statue of Liberty'." },
  { id: 18, category: "PARTY PLATFORM", text: "Draw 'A filibuster'." },
  { id: 19, category: "PARTY PLATFORM", text: "Draw 'Mount Rushmore'." },
  { id: 20, category: "PARTY PLATFORM", text: "Draw 'The White House'." },
  { id: 21, category: "PARTY PLATFORM", text: "Draw 'An election campaign'." },
  { id: 22, category: "PARTY PLATFORM", text: "Draw 'A protest march'." },
  { id: 23, category: "PARTY PLATFORM", text: "Draw 'The Liberty Bell'." },
  { id: 24, category: "PARTY PLATFORM", text: "Draw 'A gerrymandered district'." },
  { id: 25, category: "PARTY PLATFORM", text: "Draw 'A polling place'." },
  { id: 26, category: "PARTY PLATFORM", text: "Draw 'A bald eagle'." },
  { id: 27, category: "PARTY PLATFORM", text: "Draw 'The Supreme Court'." },
  { id: 28, category: "PARTY PLATFORM", text: "Draw 'Signing a bill into law'." },
  { id: 29, category: "PARTY PLATFORM", text: "Draw 'A campaign fundraiser'." },
  { id: 30, category: "PARTY PLATFORM", text: "Draw 'A political scandal'." },
  { id: 31, category: "GLAD-HANDING", text: "Do 10 push-ups in 30 seconds." },
  { id: 32, category: "GLAD-HANDING", text: "Balance on one foot for one minute." },
  { id: 33, category: "GLAD-HANDING", text: "Pat your head and rub your stomach at the same time for 30 seconds." },
  { id: 34, category: "GLAD-HANDING", text: "Do 20 jumping jacks." },
  { id: 35, category: "GLAD-HANDING", text: "Hold a plank for one minute." },
  { id: 36, category: "GLAD-HANDING", text: "Try to touch your nose with your tongue." },
  { id: 37, category: "GLAD-HANDING", text: "Spin around 10 times and then walk in a straight line." },
  { id: 38, category: "GLAD-HANDING", text: "Juggle two objects for 30 seconds." },
  { id: 39, category: "GLAD-HANDING", text: "Name all 50 states in alphabetical order in 2 minutes." },
  { id: 40, category: "GLAD-HANDING", text: "Talk for one minute without using the letter 'E'." },
  { id: 41, category: "GLAD-HANDING", text: "Do an impersonation of a famous politician." },
  { id: 42, category: "GLAD-HANDING", text: "Fold a paper airplane that flies at least 10 feet." },
  { id: 43, category: "GLAD-HANDING", text: "Recite the alphabet backwards." },
  { id: 44, category: "GLAD-HANDING", text: "Build a house of cards at least 3 levels high." },
  { id: 45, category: "GLAD-HANDING", text: "Do a cartwheel (or attempt one safely)." },
  { id: 46, category: "CHICKEN DINNER", text: "Sing the first verse of the national anthem." },
  { id: 47, category: "CHICKEN DINNER", text: "Recite the Pledge of Allegiance." },
  { id: 48, category: "CHICKEN DINNER", text: "Give a 1-minute acceptance speech for winning the presidency." },
  { id: 49, category: "CHICKEN DINNER", text: "Sing 'Yankee Doodle'." },
  { id: 50, category: "CHICKEN DINNER", text: "Recite a famous line from a political movie." },
  { id: 51, category: "CHICKEN DINNER", text: "Hum the theme song to a political TV show (e.g., The West Wing)." },
  { id: 52, category: "CHICKEN DINNER", text: "Sing 'Twinkle, Twinkle, Little Star' in an opera voice." },
  { id: 53, category: "CHICKEN DINNER", text: "Deliver the 'I have a dream' speech intro by Martin Luther King Jr." },
  { id: 54, category: "CHICKEN DINNER", text: "Read a section of the rules page in a foreign accent." },
  { id: 55, category: "CHICKEN DINNER", text: "Give a dramatic reading of a famous nursery rhyme." },
  { id: 56, category: "CHICKEN DINNER", text: "Sing the 'Happy Birthday' song as if you were a rock star." },
  { id: 57, category: "CHICKEN DINNER", text: "Recite the opening of the Declaration of Independence." },
  { id: 58, category: "CHICKEN DINNER", text: "Improvise a campaign jingle for yourself." },
  { id: 59, category: "CHICKEN DINNER", text: "Make up a short rap about politics." },
  { id: 60, category: "CHICKEN DINNER", text: "Tell a political joke." },
  { id: 61, category: "PUPPET MASTER", text: "Get another player to act out 'Mowing the lawn'." },
  { id: 62, category: "PUPPET MASTER", text: "Get another player to act out 'Baking a cake'." },
  { id: 63, category: "PUPPET MASTER", text: "Get another player to act out 'Changing a flat tire'." },
  { id: 64, category: "PUPPET MASTER", text: "Get another player to act out 'Going fishing'." },
  { id: 65, category: "PUPPET MASTER", text: "Get another player to act out 'Building a snowman'." },
  { id: 66, category: "PUPPET MASTER", text: "Get another player to act out 'Playing the violin'." },
  { id: 67, category: "PUPPET MASTER", text: "Get another player to act out 'Conducting an orchestra'." },
  { id: 68, category: "PUPPET MASTER", text: "Get another player to act out 'Riding a rollercoaster'." },
  { id: 69, category: "PUPPET MASTER", text: "Get another player to act out 'A bird flying'." },
  { id: 70, category: "PUPPET MASTER", text: "Get another player to act out 'A cat chasing a mouse'." },
  { id: 71, category: "PUPPET MASTER", text: "Get another player to act out 'Directing traffic'." },
  { id: 72, category: "PUPPET MASTER", text: "Get another player to act out 'Hitting a home run'." },
  { id: 73, category: "PUPPET MASTER", text: "Get another player to act out 'A magic trick'." },
  { id: 74, category: "PUPPET MASTER", text: "Get another player to act out 'Doing laundry'." },
  { id: 75, category: "PUPPET MASTER", text: "Get another player to act out 'Painting a masterpiece'." },
  { id: 76, category: "RANDOM", text: "Scandal! Lose 5 million Popular Votes." },
  { id: 77, category: "RANDOM", text: "A wealthy donor contributes to your campaign. Gain $10 million." },
  { id: 78, category: "RANDOM", text: "You get a major endorsement. Gain 10 million Popular Votes." },
  { id: 79, category: "RANDOM", text: "Gaffe on the campaign trail. Lose your next turn." },
  { id: 80, category: "RANDOM", text: "Polls show you surging in a swing state. Gain 10 Electoral Votes from a state of your choice (if available)." },
  { id: 81, category: "RANDOM", text: "Your campaign bus breaks down. Pay $2 million for repairs." },
  { id: 82, category: "RANDOM", text: "Give $1 million to the player on your left." },
  { id: 83, category: "RANDOM", text: "Collect $1 million from every other player." },
  { id: 84, category: "RANDOM", text: "Swap your total cash with any other player." },
  { id: 85, category: "RANDOM", text: "Go to D.C. immediately. Collect $10 million." },
  { id: 86, category: "RANDOM", text: "You must trade one of your Gerrymander cards with a random one from another player." },
  { id: 87, category: "RANDOM", text: "A rival campaign runs a negative ad. All other players take $1 million from you." },
  { id: 88, category: "RANDOM", text: "You win a debate! Gain 5 million Popular Votes." },
  { id: 89, category: "RANDOM", text: "Tax audit! Pay the bank $5 million." },
  { id: 90, category: "RANDOM", text: "Grassroots fundraising success! Gain $5 million." }
];
