
export interface Wildcard {
  id: number;
  category: string;
  text: string;
}

export const wildcards: Wildcard[] = [
  { id: 1, category: "FEEL YOUR PAIN", text: "Act out 'Walking on hot coals'." },
  { id: 2, category: "FEEL YOUR PAIN", text: "Act out 'Winning the lottery'." },
  { id: 3, category: "FEEL YOUR PAIN", text: "Act out 'Getting a root canal'." },
  { id: 4, category: "FEEL YOUR PAIN", text: "Act out 'Pulling a rabbit out of a hat'." },
  { id: 5, category: "FEEL YOUR PAIN", text: "Act out 'Raining cats and dogs'." },
  { id: 6, category: "FEEL YOUR PAIN", text: "Act out 'Scuba diving with sharks'." },
  { id: 7, category: "FEEL YOUR PAIN", text: "Act out 'Climbing Mount Everest'." },
  { id: 8, category: "FEEL YOUR PAIN", text: "Act out 'A bad hair day'." },
  { id: 9, category: "FEEL YOUR PAIN", text: "Act out 'Being chased by a bear'." },
  { id: 10, category: "FEEL YOUR PAIN", text: "Act out 'Trying to assemble IKEA furniture'." },
  { id: 11, category: "FEEL YOUR PAIN", text: "Act out 'Figure skating in a competition and one of your blades breaks'." },
  { id: 12, category: "FEEL YOUR PAIN", text: "Act out 'Santa Claus squeezing down the chimney to deliver gifts'." },
  { id: 13, category: "FEEL YOUR PAIN", text: "Act out 'Waking up late for an important meeting'." },
  { id: 14, category: "FEEL YOUR PAIN", text: "Act out 'Parallel parking a car'." },
  { id: 15, category: "FEEL YOUR PAIN", text: "Act out 'A toddler's temper tantrum'." },
  { id: 16, category: "PARTY PLATFORM", text: "Draw 'Barking up the wrong tree'." },
  { id: 17, category: "PARTY PLATFORM", text: "Draw 'Actions speak louder than words'." },
  { id: 18, category: "PARTY PLATFORM", text: "Draw 'Go back to the drawing board'." },
  { id: 19, category: "PARTY PLATFORM", text: "Draw 'Don't cry over spilled milk'." },
  { id: 20, category: "PARTY PLATFORM", text: "Draw 'Play it by ear'." },
  { id: 21, category: "PARTY PLATFORM", text: "Draw 'Stuck between a rock and a hard place'." },
  { id: 22, category: "PARTY PLATFORM", text: "Draw 'A protest march'." },
  { id: 23, category: "PARTY PLATFORM", text: "Draw 'A bird in the hand is worth two in the bush'." },
  { id: 24, category: "PARTY PLATFORM", text: "Draw 'Someone watching the Super Bowl while eating nachos'." },
  { id: 25, category: "PARTY PLATFORM", text: "Draw 'An elephant taking a dust bath'." },
  { id: 26, category: "PARTY PLATFORM", text: "Draw 'A bald eagle catching a fish out of a river'." },
  { id: 27, category: "PARTY PLATFORM", text: "Draw 'Someone playing a game where they have to draw a word or phrase and have the other people guess what is being drawn'." },
  { id: 28, category: "PARTY PLATFORM", text: "Draw 'Signing a bill into law'." },
  { id: 29, category: "RANDOM", text: "Have one candidate who is NOT wearing eyeglasses give one of their Electoral Vote chips (or $10 million if they have no EV chips) to a candidate who is wearing eyeglasses (or contacts)'." },
  { id: 30, category: "PARTY PLATFORM", text: "Draw 'Making a cup of coffee using a coffee machine'." },
  { id: 31, category: "GLAD-HANDING", text: "Do 8 push-ups within 60 seconds." },
  { id: 32, category: "GLAD-HANDING", text: "Stand on one leg, pat your head with your right hand and rub your belly with your left hand, all while singing, \"I'm a Little Teapot\"." },
  { id: 33, category: "GLAD-HANDING", text: "Take 3 non-breakable, non-sharp, non-flaming items (tennis balls, golf balls, etc) and juggle them for at least 5 seconds." },
  { id: 34, category: "GLAD-HANDING", text: "Do 20 jumping jacks." },
  { id: 35, category: "GLAD-HANDING", text: "Hold a plank for 30 seconds. Your body should be supported only by your toes and forearms." },
  { id: 36, category: "GLAD-HANDING", text: "Hold a broom or mop handle with both hands, about shoulder width apart. Then bend over so the handle is as close to the floor as you can get it. Step over the handle without falling, one foot at a time." },
  { id: 37, category: "GLAD-HANDING", text: "Spin around in a circle 10 times within 10 seconds and then walk in a straight line." },
  { id: 38, category: "GLAD-HANDING", text: "Sit in a chair with both feet flat on the floor. Lift your right foot a few inches and make clockwise circles with your foot. At the same time, draw the number 6 in the air with your right index finger." },
  { id: 39, category: "GLAD-HANDING", text: "Get on your knees and place your elbows on the floor in front of you. Now take one arm and place it on your low back, then place the other arm on your low back without falling forward." },
  { id: 40, category: "GLAD-HANDING", text: "Draw a standard analog clock, showing the time of 3:40, with your eyes closed the entire time." },
  { id: 41, category: "GLAD-HANDING", text: "You have one minute to get an egg to balance on one of its ends. It must stay upright for at least 3 seconds." },
  { id: 42, category: "GLAD-HANDING", text: "Fold a paper airplane that flies at least 10 feet." },
  { id: 43, category: "GLAD-HANDING", text: "Recite the alphabet backwards." },
  { id: 44, category: "GLAD-HANDING", text: "Do 'the floss' dance move for 10 seconds." },
  { id: 45, category: "GLAD-HANDING", text: "Hold a wall sit for 30 seconds. There must be a 90 degree angle between your thighs and torso." },
  { id: 46, category: "CHICKEN DINNER", text: "Sing the first verse of the national anthem (the song as typically sung at sporting events), but do it in the style of a boy band." },
  { id: 47, category: "CHICKEN DINNER", text: "Sing the Pledge of Allegiance in the style of a country song." },
  { id: 48, category: "CHICKEN DINNER", text: "Give a 1-minute acceptance speech for winning the presidency, but it must be in the form of a rap song." },
  { id: 49, category: "CHICKEN DINNER", text: "Sing the first two verses of 'Yesterday' by the Beatles, but sing it like Lady Gaga would sing it." },
  { id: 50, category: "CHICKEN DINNER", text: "Sing the first two verses of 'Rudolph, the Red-Nosed Reindeer' in the style of the Rolling Stones." },
  { id: 51, category: "CHICKEN DINNER", text: "Hum the theme song to a political TV show (e.g., The West Wing)." },
  { id: 52, category: "CHICKEN DINNER", text: "Sing 'Twinkle, Twinkle, Little Star' in the style of a death metal band." },
  { id: 53, category: "RANDOM", text: "Every candidate must give you $1 million each because of your sparkling intellect, quick wit and stunning good looks." },
  { id: 54, category: "RANDOM", text: "You may place yourself in any state you want, and you get $5 million from the bank." },
  { id: 55, category: "CHICKEN DINNER", text: "Give a dramatic reading of a famous nursery rhyme." },
  { id: 56, category: "CHICKEN DINNER", text: "Sing the 'Happy Birthday' song as if you were an opera singer." },
  { id: 57, category: "RANDOM", text: "Every candidate not wearing a wristwatch must give you 2 million of their Popular Votes (or $2 million in they have no PVs)." },
  { id: 58, category: "CHICKEN DINNER", text: "Improvise a campaign jingle for yourself. It must include your last name and at least one reason why people should vote for you." },
  { id: 59, category: "RANDOM", text: "Send any candidate to any state you want. They must also give you $2 million, and they lose their next turn." },
  { id: 60, category: "RANDOM", text: "Every candidate wearing socks must give you $1 million." },
  { id: 61, category: "PUPPET MASTER", text: "Get another player to act out 'Mowing the lawn'." },
  { id: 62, category: "PUPPET MASTER", text: "Get another player to act out 'Baking a cake'." },
  { id: 63, category: "PUPPET MASTER", text: "Get another player to act out 'Changing a flat tire'." },
  { id: 64, category: "PUPPET MASTER", text: "Get another player to act out 'Changing a baby's diaper'." },
  { id: 65, category: "PUPPET MASTER", text: "Get another player to act out 'Giving a bath to a large dog'." },
  { id: 66, category: "PUPPET MASTER", text: "Get another player to act out 'Playing the violin'." },
  { id: 67, category: "PUPPET MASTER", text: "Get another player to act out 'Conducting an orchestra'." },
  { id: 68, category: "PUPPET MASTER", text: "Get another player to act out 'Riding a rollercoaster'." },
  { id: 69, category: "PUPPET MASTER", text: "Get another player to act out 'A bird flying'." },
  { id: 70, category: "PUPPET MASTER", text: "Get another player to act out 'Playing the saxophone'." },
  { id: 71, category: "PUPPET MASTER", text: "Get another player to act out 'Directing traffic'." },
  { id: 72, category: "PUPPET MASTER", text: "Get another player to act out 'Making a snowball'." },
  { id: 73, category: "PUPPET MASTER", text: "Get another player to act out 'Throwing a bowling ball down the lane'." },
  { id: 74, category: "PUPPET MASTER", text: "Get another player to act out 'Doing laundry'." },
  { id: 75, category: "PUPPET MASTER", text: "Get another player to act out 'Painting a masterpiece'." },
  { id: 76, category: "RANDOM", text: "Every candidate with braces must give you 2 million of their Popular Votes (or $2 million if they have no PVs)." },
  { id: 77, category: "RANDOM", text: "Every candidate under age 60 must give you $1 million." },
  { id: 78, category: "RANDOM", text: "Send any candidate to Mississippi, where they miss a turn. You also get to take either 3 million of their Popular Votes or $3 million." },
  { id: 79, category: "RANDOM", text: "Take 5 million Popular Votes and $5 million from the candidate you think is most likely to win the game. (If no one has these amounts, then take whatever cash and PVs they do have.)." },
  { id: 80, category: "RANDOM", text: "The candidate closest to age 40 (over or under) gets sent to Hawaii and must give $1 million to each of the other candidates." },
  { id: 81, category: "RANDOM", text: "You got secretly recorded at a fundraiser saying that teachers are just 'glorified babysitters'. You now must give $5 million to the NEA, then take yourself to Illinois to spend a day as a 5th grade substitute teacher. You also lose a turn." },
  { id: 82, category: "RANDOM", text: "Each candidate with brown hair must give you $1 million." },
  { id: 83, category: "RANDOM", text: "The candidate to your right overcharged the government by 300% for hotel rooms used by the Secret Service. That candidate must give you 10 million Popular Votes and $5 million to keep quiet." },
  { id: 84, category: "RANDOM", text: "Swap one of your unplayed Gerrymander cards with an unplayed Gerrymander card of another candidate. You may not see the card of the other player before you swap it." },
  { id: 85, category: "RANDOM", text: "Go to D.C. immediately. Collect $10 million." },
  { id: 86, category: "RANDOM", text: "You release an email from the youngest candidate, showing they want to eliminate Social Security and instead give everyone under age 30 a Starbucks card good for a daily free latte. This candidate now loses 20 million Popular Votes." },
  { id: 87, category: "RANDOM", text: "The Bank of China wants to start collecting on the $600 million they loaned you to build an apartment tower with your name on it. Pay $8 million now." },
  { id: 88, category: "RANDOM", text: "Select one candidate to give one of their Electoral Vote chips (their choice) to another candidate of your choosing. If they have no EV chip to give, then they must give the other candidate $5 million." },
  { id: 89, category: "RANDOM", text: "The tallest candidate must give $1 million to each of the other candidates." },
  { id: 90, category: "RANDOM", text: "Send any candidate to D.C., where they lose a turn but do NOT collect any cash." }
];
